# Generated by Django 3.0.3 on 2020-03-17 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Admin Group', max_length=25)),
                ('status', models.CharField(default='ACTIVE', max_length=25)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('org_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('SuperStockist', 'Super Stockist'), ('Stockist', 'Stockist'), ('Retailer', 'Retailer')], default='Retailer', max_length=20)),
                ('status', models.CharField(default='INACTIVE', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Administrator', max_length=50)),
                ('module', multiselectfield.db.fields.MultiSelectField(choices=[('Admin', 'Admin'), ('Product', 'Product'), ('Billing', 'Billing'), ('Batch', 'Batch'), ('Support', 'Support'), ('Offer', 'Offer')], default='Admin', max_length=41)),
                ('create', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(default='male_default.png', upload_to='profile_pics')),
                ('user_token', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(default='INACTIVE', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('force_login', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Groups')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyOwnToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.Consumer', verbose_name='Consumer')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
        migrations.AddField(
            model_name='groups',
            name='role_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.RolePermission'),
        ),
    ]
